# Generated by Django 4.1.5 on 2023-01-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2048)),
                ("reduction_url", models.CharField(max_length=2048, unique=True)),
                ("expired_at", models.DateField(null=True)),
            ],
            options={
                "db_table": "url",
            },
        ),
    ]
